import type { Job } from "./types"

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "Rudratek",
    companyLogo: "RT",
    companyColor: "#3B82F6",
    location: "Remote · USA",
    remote: true,
    type: "Full-time",
    level: "Senior",
    category: "Engineering",
    salary: { min: 140000, max: 180000, currency: "USD" },
    tags: ["React", "TypeScript", "GraphQL", "Tailwind"],
    description:
      "Join our product team and shape the future of work. You'll build delightful, performant user experiences used by thousands of companies worldwide.",
    responsibilities: [
      "Lead the architecture and development of our core React application",
      "Collaborate with product and design teams to deliver high-impact features",
      "Mentor junior engineers and conduct thorough code reviews",
      "Drive adoption of modern frontend best practices across the team",
      "Contribute to and evolve our component design system",
    ],
    requirements: [
      "3+ years of frontend development experience",
      "Strong expertise in React, TypeScript, and modern CSS",
      "Experience with design systems and component libraries",
      "Excellent communication and collaboration skills",
      "Passion for clean, testable, maintainable code",
    ],
    about:
      "Rudratek is reimagining how global teams hire and onboard talent. Backed by top-tier investors and growing fast.",
    featured: true,
    postedAt: "2025-03-12T10:00:00Z",
    applicants: 124,
    views: 3200,
  },
  {
    id: "2",
    title: "Product Designer",
    company: "Morphic Labs",
    companyLogo: "ML",
    companyColor: "#8B5CF6",
    location: "San Francisco, CA",
    remote: false,
    type: "Full-time",
    level: "Mid-level",
    category: "Design",
    salary: { min: 120000, max: 160000, currency: "USD" },
    tags: ["Figma", "Design Systems", "UX Research", "Prototyping"],
    description:
      "Own end-to-end design across our flagship product. High-impact role where your work ships daily and is used by thousands.",
    responsibilities: [
      "Own the product design process from discovery to delivery",
      "Create wireframes, prototypes, and high-fidelity designs",
      "Run user research sessions and synthesize insights",
      "Collaborate with engineers to ensure pixel-perfect implementation",
      "Maintain and evolve our design system",
    ],
    requirements: [
      "4+ years of product design experience",
      "Mastery of Figma and modern design tooling",
      "Strong portfolio showcasing end-to-end product thinking",
      "Experience with user research methodologies",
      "Startup adaptability and comfort with ambiguity",
    ],
    about:
      "Morphic Labs builds AI-native tools for creative teams. Our products are used by designers at Stripe, Notion, and Linear.",
    featured: false,
    postedAt: "2025-03-13T08:00:00Z",
    applicants: 87,
    views: 2100,
  },
  {
    id: "3",
    title: "Backend Engineer",
    company: "Velox Systems",
    companyLogo: "VS",
    companyColor: "#10B981",
    location: "Remote · Europe",
    remote: true,
    type: "Contract",
    level: "Mid-level",
    category: "Engineering",
    salary: { min: 90000, max: 120000, currency: "USD" },
    tags: ["Node.js", "PostgreSQL", "AWS", "Docker"],
    description:
      "Scale our infrastructure. Design high-throughput APIs powering millions of events per day across Europe and North America.",
    responsibilities: [
      "Design and build RESTful and GraphQL APIs",
      "Optimize database performance and data modeling",
      "Build scalable event-driven microservices",
      "Own incident response for your services",
      "Write clear technical documentation and architecture docs",
    ],
    requirements: [
      "3+ years of backend development with Node.js",
      "Solid experience with PostgreSQL or similar RDBMS",
      "Familiarity with AWS services (Lambda, SQS, RDS)",
      "Strong understanding of system design principles",
      "Experience with Docker and container orchestration",
    ],
    about:
      "Velox Systems provides real-time data infrastructure for logistics and supply chain companies across Europe and North America.",
    featured: false,
    postedAt: "2025-03-11T12:00:00Z",
    applicants: 56,
    views: 1450,
  },
  {
    id: "4",
    title: "Engineering Manager",
    company: "Strata AI",
    companyLogo: "SA",
    companyColor: "#EF4444",
    location: "New York, NY",
    remote: false,
    type: "Full-time",
    level: "Manager",
    category: "Engineering",
    salary: { min: 180000, max: 240000, currency: "USD" },
    tags: ["Leadership", "Agile", "AI/ML", "Roadmap"],
    description:
      "Lead a cross-functional team of 6–8 engineers building AI-powered analytics tools. Balance technical leadership with people management.",
    responsibilities: [
      "Lead and grow a team of 6–8 senior engineers",
      "Drive technical roadmap and quarterly planning",
      "Partner with product managers and key stakeholders",
      "Foster a culture of psychological safety and high performance",
      "Remove blockers and ensure delivery excellence",
    ],
    requirements: [
      "3+ years of engineering management experience",
      "Strong technical background ideally in ML/AI",
      "Track record of building and scaling high-performing teams",
      "Excellent stakeholder management skills",
      "Deep experience with Agile and Scrum methodologies",
    ],
    about:
      "Strata AI is the leading platform for enterprise business intelligence processing 50TB+ of data daily for Fortune 500 clients.",
    featured: true,
    postedAt: "2025-03-14T06:00:00Z",
    applicants: 43,
    views: 980,
  },
  {
    id: "5",
    title: "Full Stack Developer",
    company: "Lumen Studio",
    companyLogo: "LS",
    companyColor: "#0EA5E9",
    location: "Remote · Global",
    remote: true,
    type: "Full-time",
    level: "Mid-level",
    category: "Engineering",
    salary: { min: 100000, max: 130000, currency: "USD" },
    tags: ["Next.js", "Python", "Supabase", "TailwindCSS"],
    description:
      "A boutique product studio needing a Full Stack Developer who can move fast — from database design to pixel-perfect UI.",
    responsibilities: [
      "Build and ship full-stack features end to end",
      "Contribute to product decisions and UX discussions",
      "Maintain and improve CI/CD pipelines",
      "Participate in customer discovery calls",
      "Write clean, well-tested, documented code",
    ],
    requirements: [
      "3+ years of full-stack development experience",
      "Proficiency with Next.js and a Python framework",
      "Experience with Supabase, Firebase, or similar BaaS",
      "Strong product intuition and self-direction",
      "Comfortable in a small fast-moving team",
    ],
    about:
      "Lumen Studio partners with ambitious founders to go from 0 to 1. Remote-first team of 12 building tools people love.",
    featured: false,
    postedAt: "2025-03-07T09:00:00Z",
    applicants: 201,
    views: 5400,
  },
  {
    id: "6",
    title: "DevOps / Platform Engineer",
    company: "Axion Cloud",
    companyLogo: "AC",
    companyColor: "#F59E0B",
    location: "Austin, TX · Hybrid",
    remote: false,
    type: "Full-time",
    level: "Senior",
    category: "DevOps",
    salary: { min: 130000, max: 165000, currency: "USD" },
    tags: ["Kubernetes", "Terraform", "GCP", "Observability"],
    description:
      "Own our internal developer platform, CI/CD systems, and observability stack for mid-market SaaS companies.",
    responsibilities: [
      "Own and evolve our Kubernetes-based developer platform",
      "Build internal tooling for deployment and monitoring",
      "Improve developer experience and engineering velocity",
      "Maintain infrastructure as code with Terraform",
      "Lead incident response and blameless postmortems",
    ],
    requirements: [
      "4+ years of DevOps or platform engineering experience",
      "Deep experience with Kubernetes and Helm",
      "Proficiency with Terraform and GCP or AWS",
      "Strong grasp of SRE principles and practices",
      "Experience with observability tooling like Datadog or Grafana",
    ],
    about:
      "Axion Cloud manages cloud infrastructure for growth-stage SaaS companies scaling reliably and securely.",
    featured: false,
    postedAt: "2025-03-10T14:00:00Z",
    applicants: 78,
    views: 1900,
  },
  {
    id: "7",
    title: "Data Scientist",
    company: "Pulse Analytics",
    companyLogo: "PA",
    companyColor: "#EC4899",
    location: "Remote · USA",
    remote: true,
    type: "Full-time",
    level: "Senior",
    category: "Data",
    salary: { min: 135000, max: 175000, currency: "USD" },
    tags: ["Python", "ML", "SQL", "Spark"],
    description:
      "Build and deploy machine learning models that power our core product recommendations and business intelligence dashboards.",
    responsibilities: [
      "Design and train production ML models",
      "Build robust data pipelines with Spark and Airflow",
      "Partner with product to define and measure success metrics",
      "Communicate findings clearly to non-technical stakeholders",
      "Own the full ML lifecycle from ideation to deployment",
    ],
    requirements: [
      "4+ years of data science or ML engineering experience",
      "Strong Python and SQL skills",
      "Experience with distributed computing frameworks like Spark",
      "Solid statistics and ML fundamentals",
      "Experience deploying models to production",
    ],
    about:
      "Pulse Analytics helps growth-stage companies make smarter decisions through real-time data and predictive intelligence.",
    featured: false,
    postedAt: "2025-03-09T11:00:00Z",
    applicants: 92,
    views: 2300,
  },
  {
    id: "8",
    title: "Product Manager",
    company: "Corda Health",
    companyLogo: "CH",
    companyColor: "#14B8A6",
    location: "Boston, MA · Hybrid",
    remote: false,
    type: "Full-time",
    level: "Senior",
    category: "Product",
    salary: { min: 140000, max: 170000, currency: "USD" },
    tags: ["Roadmapping", "Healthtech", "Agile", "OKRs"],
    description:
      "Define and drive the product roadmap for our patient engagement platform used by 200+ hospitals across the US.",
    responsibilities: [
      "Own the product roadmap and quarterly OKRs",
      "Conduct user interviews and synthesize research into actionable insights",
      "Write clear, detailed product requirements and specs",
      "Work closely with engineering and design to ship great products",
      "Align stakeholders across clinical and technical teams",
    ],
    requirements: [
      "5+ years of product management experience",
      "Experience in healthtech or regulated industries",
      "Strong analytical and data-driven decision making",
      "Excellent written and verbal communication",
      "Track record of shipping impactful products on time",
    ],
    about:
      "Corda Health is modernizing patient engagement for health systems. Our platform is trusted by 200+ hospitals and 3M+ patients.",
    featured: true,
    postedAt: "2025-03-13T15:00:00Z",
    applicants: 67,
    views: 1750,
  },
]